### ISSUE TITLE
8PSK mapping

### ISSUE THREAD

**Issue by F5OEO** [natsfr/LimeSDR_DVBSGateware#2]
New LUT and different packing (2*Symbols(3bit) each I12).
Bit config in fpga memory to select LUT

**Comment by natsfr** [comment]
Status: Prototyped, need testing.

**Comment by F5OEO** [comment]
![8PSKfpgagood](https://user-images.githubusercontent.com/6190918/60270377-9a4fba00-98f0-11e9-8a76-2371c07ab3f3.JPG)
Seems to work OK .
